nodeSelector:
  topology.kubernetes.io/region: at-vie
  topology.kubernetes.io/zone: at-vie-1

tls:
  secretName: ldap-2.deepsquare.internal-secret

persistence:
  storageClassName: '389ds-at-vie-nfs'

# Extra volume mounts
volumeMounts:
  - name: custom-ldifs
    mountPath: /ldifs-custom
    readOnly: true

# Extra volumes (use it to mount secrets like ldif)
volumes:
  - name: custom-ldifs
    configMap:
      name: custom-ldifs
      defaultMode: 432

config:
  dmPassword:
    secretName: '389ds-secret'
    key: 'dm-password'
  inf:
    secretName: ''
    key: 'container.inf'
  suffixName: 'dc=hpc,dc=deepsquare,dc=run'

initChownData:
  enabled: true
