apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBeS6XI5djqctocOgUNrpgyUdz9YybKtSUP75m15hKUtNtDq1FztrJfYHjY+eLjFovrR51VyHCBGFvUk+2X+GktkseEPwhgq/Jk+xpI9pePvF1IYnqxPWnRBPiqQtpiXIoCG2keX54LMiw6vIeesx9MLGuaHUfb8vnN/7JDjWKyeugBJn5DgGO0hB18kO67UIwGsnd74oE9/byiBfveXd8h1dFd7oFznHLR0+g4J1DQ2SySaf8O5VSgi4bFCv8cbgqK3TzQAK+MiNyPR4ymfYGF8SgH+t8mKpEGxDh9SN0IdQ7m3lcedFN35ryFy2OyRlXgGQojmbseBENMMBu0Itv9yANsMrWR6PvoI9rl79XdE5vYuK7ELRKuTrrBrXQE8lHClpzMs8X/n+oTIMq041GYEc9Ru+AAJl8DZD9kKrXFJ/m83JCxJS6cH7qKZXUBanl0IBGltRFlPgGNSNav/PCkT6k8lpz8gg4of5HOE/5nFnyceT+7JheQcyxs9mN98LdkRdBqQWqMRA/a6vluEv953MgEyPRJPqrsewzvGajzB1zImIXMVS4Z5sBaytnYT9TJ+90iyqLlTCxZ/A7/S3FWPVv8XDCwMTRTDcSZiFLvNU35NGVX+gBDqptx2h/3Lz022yvGBP08NifqX84iBFfzjnXQ1xkz3xdbCrlJV3sGw34B8peRbZM8gZ7m5HFQM8Vl0EI34S9bEywV5OkFDr/a1ugTQHK3HSVbkIgk/xGORA==
    admin-user: AgCAwBbAd3bsbqFsv0T5xSusU8uXjOEInaGWF7e7zafLSskNBOl2CKJA+pNDtiKHHztMMwbwuWs+qgQudyxmI98rXSg9uW+mLSiNlNLUs9QxEIRIk1ZdSpUZw1q9fn9aZ6uvu6jzBMrmEgmiGVPww7lnDROZ+4PG9f5Av8FdJQFYS+IhEev8rfwdsc0M/UFUTQDW2NLMT/OKBboTHdOcK0DwZmviUhY5qPqtl6lcQVntpPvZ0R3L+joUwNIsL2shmr7p5FpOEigtrLUFOumDvwFFwbKFM0YI8gtAiKY+2g93csQj+Em5L61igBi+zNq8vHS9liIGrdMcHcU2mteMDpJIuz+Qg7cwvERy1iKJKGmuVkQ1zxVCCpy8eyhvwCQbS/BErR6xVqFYaIeNhpJAW36rHacKWRi+VbuZtG+ya4EG++DwqcVqvA8q9vExntI8kuEl25rv+OKtimaTOfuxS8Il46pAeNPZp7ZyFIVXZU29FWwhYMa0yQDOWEfYGU+lf7sznPPI1YcdnSbF6lh7Q6+1U7F0JvuFHsgBtHABn1Ok3wLNSbAvacxOluTbVGcK7AyzePX2D3/yTz73UjjvvHmjXDr+M2QCCn8uBd9uM6X3WbT9Mml5Gy/NcSn0JSKkgKYxgsY7X1kz1m1PY5XU1CcJqzucLO6b9SqwFdUHs4uCZrdTcbcCfPmW3X3EOAFwhfkKOU01Sg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque

