apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCqmSDN5w8WJRe6+U4xttjoFDMrsKiv4piAvbacSnq4WekadZxeUYiV+fsfyDrfg7gA3pKw+yc43DLeDPueiPGT53TA9jHNMMUiTJE/CFaXt7SZxZKZTIJNZ2QaR/HMVJAd9vFDoj3j/BEwr8yOHQxr5epFBCxdU8ZDszbezhFLslKidGWya4V5Ui6MNgtOU7KwUefWXoDKJoohhI+8X2XtLzcPQpjf7bcbFMA59U8/DnbDQVsVSkkrK6WSU0sW/qGInDXHY8s6UdkvrfwH9Jamwg4nCl3gR1x7d9FSnH21f2XjJZFyL2fbFN7Z2QYEz26LqdCEn6cIC8/43LSu2YQVZAZXIB8R0+RoRw4oUZSLTL9EcxEB6509soGyB2sI9+tVx6DrwSrqbfdE8A8AHEJulw9U3/DkQmH+oHmLewoWZZzL9m+z5QAxoUKB7ApPgkktIpRFiTUC+f9s85A15CXUa2kVYZ+Kt9JfLbPky3GlyWjmOayV2R6SruvpWU7Ao0XzYKsqkH10/jxRpWFiDvm6NuwTM3hWO9Fnw/JKtA5XIFHD9A4e9W0w6Es9HAz+hL8AJsaZUTMrzYbXtPNceHXu5c5wHVkpagU42x4/QXp+EHxnreTOfOvo9FsAbAFEIu1Nnw1+uM4BGlvbfz0OAW3rXIQx1MHs0drcNLpCbdnjRnv7fHng+nVSwqha8vutGDHbo/TtS+V7U9ing6fW5fFNfC/D6ioBwIu9l4vS0hwzDw==
    admin-user: AgAQuWVWUdFzXdaqdYQNTSXZloAab524QZAYhEizUwOoxXkJ23nC57vGcPx8xdQWFcpHgI6fOLx/60fXUHe6AHnEsZVp4AZ+obki/pmFegtD71ho22Nrt0JcKwRpFMy+sgON3MmTW31ik99pwCsILT7G3TlvInMCDA4ejb07+rdmjQHpt204xDdOlZDKEHxg+SzLHEmm0VZXfz0mcrY/9DKVNbdnh62xRcZsV18+mna7Ur6FKp1kCpoF1dYma1ibx6vHzqpEu6JpzfbRXbEaogbQM1YgVfdI3Ql3+F7F2MM1oKVhHO8Vtgaq3VqOu8lDIpq06u7jyyQF7PoVP61JGGjDQcWniUFysUY7mrqnE7kdLqG9CV5dMLhzdT8PQIb5HWbpv65yINdksXJWCR7wT505ZwYeK8Udit1F0es//mqN4H7ghb1dgu+PlrPSv1rX0Fshh57euYnIqJpNTLUDlwL3UxpNCHHjCnOKaKiNscvdS8tG8SUJlWmML+s+GYC2IUVMb3i3INkmFJYkXI6eIhVsAVLPXhuzm6l+lxUp2rXaPsTA2qulYoYhOft4ZCRUYOEY954Vb6RaNKvy5RmbfCef2H9axefajn+Dfq26Y/4/yhdnkyKfpTDOF3zI1h3QSn6eo11FmCGqGvgDaVGVZar6RTUivYxEyUTSsqzPILOrcXo2I6E7Ya+pWc/TQ/DBYuD/SsEMTA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque

