apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slurm-cluster-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: slurm-cluster
  source:
    repoURL: git@github.com:squarefactory/cluster-factory-ce.git
    targetRevision: HEAD
    path: helm/slurm-cluster
    helm:
      releaseName: slurm-cluster

      values: |
        sssd:
          # secret containing sssd.conf
          # Will be mounted in /secrets/sssd
          secretName: sssd-secret

        munge:
          # secret containing munge.key
          # Will be mounted in /secrets/munge
          secretName: munge-secret

        slurmConfig:
          clusterName: reindeerpizza

          compute:
            srunPortRange: 60001-63000
            debug: debug5

          accounting: |
            AccountingStorageType=accounting_storage/slurmdbd
            AccountingStorageExternalHost=slurmdb.csquare.gcloud:6819
            AccountingStorageHost=slurmdb.csquare.gcloud
            AccountingStoragePort=6819
            AccountingStorageTRES=gres/gpu

          controller:
            host: slurmctl.ch1.csquare.run
            parameters: enable_configless
            debug: debug5

            # secret containing jwt_hs256.key
            # Will be mounted in /secrets/slurm
            jwt:
              secretName: slurm-secret

          nodes: |
            NodeName=cn[1-10]  CPUs=32 Boards=1 SocketsPerBoard=1 CoresPerSocket=16 ThreadsPerCore=2 RealMemory=128473 Gres=gpu:2
            NodeName=cn[11-12] CPUs=32 Boards=1 SocketsPerBoard=1 CoresPerSocket=16 ThreadsPerCore=2 RealMemory=128473 Gres=gpu:2

          partitions: |
            PartitionName=main Nodes=cn[1-10] Default=YES MaxTime=INFINITE State=UP OverSubscribe=NO TRESBillingWeights="CPU=2.6,Mem=0.25G,GRES/gpu=24.0"
            PartitionName=main-beeond Nodes=cn[1-10] Default=NO MaxTime=INFINITE State=UP OverSubscribe=EXCLUSIVE TRESBillingWeights="CPU=2.6,Mem=0.25G,GRES/gpu=24.0"
            PartitionName=private Nodes=cn[11-12] Default=NO MaxTime=INFINITE State=UP OverSubscribe=NO Hidden=YES AllowQos=admin

          gres: |
            NodeName=cn[1-12] File=/dev/nvidia[0-3] AutoDetect=nvml

          # Extra slurm.conf configuration
          extra: |
            JobCompType=jobcomp/report
            JobCompLoc=https://slurm:f_4UyDHC7%21w%24Cc2KSHFv@slurm.accounting.csquare.gcloud/report
            JobAcctGatherType=jobacct_gather/cgroup
            #MailProg=/usr/bin/fakemail



        controller:
          image:
          replicas: 1

          command: ['sh', '-c' 'update-ca-trust && /init']

          imagePullSecrets:
            - name: ghcr-marc-secret

          tmp:
            medium: ''
            size: 50Gi

          persistence:
            storageClassName: ''
            accessModes: ['ReadWriteOnce']
            size: 50Gi
            selectorLabels:
              app: slurm-controller

          # Extra volume mounts
          volumeMounts:
            - name: slurmctl-ssh
              mountPath: /root/.ssh
            - name: ca-cert
              mountPath: /etc/pki/ca-trust/source/anchors/csquare.gcloud.pem
              subPath: csquare.gcloud.pa.pem

          # Extra volumes
          volumes:
            - name: slurmctl-ssh
              secret:
                secretName: slurmctl-ssh-secret
                defaultMode: 0600
            - name: ca-cert
              secret:
                secretName: local-ca-secret

          # Extra volume claims
          volumeClaimTemplates: []

          service:
            port: 6817
            externalIPs: [10.10.2.152]

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: slurm-cluster

  syncPolicy:
    automated:
      prune: false # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions: []
    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 3m # the maximum amount of time allowed for the backoff strategy
