apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slurm-cluster-reindeer-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: slurm-cluster
  source:
    repoURL: git@github.com:squarefactory/cluster-factory-ce.git
    targetRevision: HEAD
    path: helm/slurm-cluster
    helm:
      releaseName: slurm-cluster-reindeer

      values: |
        sssd:
          # secret containing sssd.conf
          # Will be mounted in /secrets/sssd
          secretName: sssd-secret

        munge:
          # secret containing munge.key
          # Will be mounted in /secrets/munge
          secretName: munge-secret

        slurmConfig:
          clusterName: reindeerpizza

          compute:
            srunPortRangeStart: 60001
            srunPortRangeEnd: 63000
            debug: debug5

          accounting: |
            AccountingStorageType=accounting_storage/slurmdbd
            AccountingStorageHost=slurmdbd.csquare.gcloud
            AccountingStoragePort=6819
            AccountingStorageTRES=gres/gpu

          controller:
            parameters: enable_configless
            debug: debug5

          defaultResourcesAllocation: |
            DefCpuPerGPU=4
            DefMemPerCpu=7000

          nodes: |
            NodeName=cn[1-11]  CPUs=32 Boards=1 SocketsPerBoard=1 CoresPerSocket=16 ThreadsPerCore=2 RealMemory=128473 Gres=gpu:4
            NodeName=cn12 CPUs=32 Boards=1 SocketsPerBoard=1 CoresPerSocket=16 ThreadsPerCore=2 RealMemory=128473 Gres=gpu:4

          partitions: |
            PartitionName=main Nodes=cn[1-11] Default=YES MaxTime=INFINITE State=UP OverSubscribe=NO TRESBillingWeights="CPU=2.6,Mem=0.25G,GRES/gpu=24.0"
            PartitionName=main-beeond Nodes=cn[1-11] Default=NO MaxTime=INFINITE State=UP OverSubscribe=EXCLUSIVE TRESBillingWeights="CPU=2.6,Mem=0.25G,GRES/gpu=24.0"
            PartitionName=private Nodes=cn12 Default=NO MaxTime=INFINITE State=UP OverSubscribe=NO Hidden=YES AllowQos=admin

          gres: |
            NodeName=cn[1-12] File=/dev/nvidia[0-3] AutoDetect=nvml

          # Extra slurm.conf configuration
          extra: |
            LaunchParameters=enable_nss_slurm
            DebugFlags=Script,Gang,SelectType
            TCPTimeout=5

            # MPI stacks running over Infiniband or OmniPath require the ability to allocate more
            # locked memory than the default limit. Unfortunately, user processes on login nodes
            # may have a small memory limit (check it by ulimit -a) which by default are propagated
            # into Slurm jobs and hence cause fabric errors for MPI.
            PropagateResourceLimitsExcept=MEMLOCK

            ProctrackType=proctrack/cgroup
            TaskPlugin=task/cgroup
            SwitchType=switch/none
            MpiDefault=pmix_v2
            ReturnToService=2 #temp
            GresTypes=gpu
            PreemptType=preempt/qos
            PreemptMode=REQUEUE
            PreemptExemptTime=-1
            Prolog=/etc/slurm/prolog.d/*
            Epilog=/etc/slurm/epilog.d/*

            # Federation
            FederationParameters=fed_display

            JobCompType=jobcomp/report
            JobCompLoc=https://slurm:f_4UyDHC7%21w%24Cc2KSHFv@slurm.accounting.csquare.gcloud/report
            JobAcctGatherType=jobacct_gather/cgroup
            #MailProg=/usr/bin/fakemail

        controller:
          image: 'ghcr.io/squarefactory/slurm-docker:0.1.1-slurmctl-reindeer'
          replicas: 1

          command: ['sh', '-c', 'update-ca-trust && /init']

          imagePullSecrets:
            - name: ghcr-marc-secret

          persistence:
            storageClassName: ''
            accessModes: ['ReadWriteOnce']
            size: 50Gi
            selectorLabels:
              app: slurm-controller
              failure-domain.beta.kubernetes.io/region: ch-sion
              failure-domain.beta.kubernetes.io/zone: ch-sion-1

          initContainers:
            - name: init-perms-ssh
              image: busybox:1.34.1
              command:
                - sh
                - -c
                - |-
                  cp -RLp /in-ssh/* /out-ssh/
                  chmod -R 0600 /out-ssh/
              volumeMounts:
                - name: slurmctl-ssh
                  mountPath: /in-ssh
                - name: root-ssh-dir
                  mountPath: /out-ssh

          # secret containing jwt_hs256.key
          # Will be mounted in /secrets/slurm
          jwt:
            secretName: slurm-secret

          prologsConfigMap: 'slurmctl-reindeer-prologs'
          epilogsConfigMap: 'slurmctl-reindeer-epilogs'

          nodeSelector:
            failure-domain.beta.kubernetes.io/region: ch-sion
            failure-domain.beta.kubernetes.io/zone: ch-sion-1

          # Extra volume mounts
          volumeMounts:
            - name: root-ssh-dir
              mountPath: /root/.ssh
            - name: ca-cert
              mountPath: /etc/pki/ca-trust/source/anchors/csquare.gcloud.ca.pem
              subPath: csquare.gcloud.ca.pem

          # Extra volumes
          volumes:
            - name: slurmctl-ssh
              secret:
                secretName: slurmctl-ssh-secret
                defaultMode: 384
            - name: ca-cert
              secret:
                secretName: local-ca-secret
            - name: root-ssh-dir
              emptyDir:
                medium: "Memory"

          # Extra volume claims
          volumeClaimTemplates: []

          servicePerReplica:
            port: 6817
            annotations:
              metallb.universe.tf/address-pool: ch-sion-1-pool
            loadBalancerIP: 10.10.4.152
            type: LoadBalancer

        login:
          enabled: true
          image: 'ghcr.io/squarefactory/slurm-docker:0.1.2-login-reindeer'
          replicas: 2

          command: ['sh', '-c', 'update-ca-trust && /init']

          imagePullSecrets:
            - name: ghcr-marc-secret

          sshd:
            secretName: login-sshd-secret

          nodeSelector:
            failure-domain.beta.kubernetes.io/region: ch-sion
            failure-domain.beta.kubernetes.io/zone: ch-sion-1

          networks: '[{
            "name": "slurm-cluster-reindeer-login-net",
            }]'

          # Extra volume mounts
          volumeMounts:
            - name: ca-cert
              mountPath: /etc/pki/ca-trust/source/anchors/csquare.gcloud.ca.pem
              subPath: csquare.gcloud.ca.pem
            - name: slurm-login-reindeer-profile
              mountPath: /etc/profile.d/z00_lmod.sh
              subPath: z00_lmod.sh
            - name: slurm-login-reindeer-profile
              mountPath: /etc/profile.d/z01_lmod_env.sh
              subPath: z01_lmod_env.sh
            - name: slurm-login-reindeer-contlist
              mountPath: /usr/local/bin/contlist
              subPath: contlist
            - name: ldap-users-reindeer-pvc
              mountPath: /home/ldap-users
            - name: jobs-logs-reindeer-pvc
              mountPath: /opt/jobs-logs
            - name: images-reindeer-pvc
              mountPath: /opt/images
            - name: experiments-reindeer-pvc
              mountPath: /opt/experiments
            - name: software-sion-csquare-run
              mountPath: /opt/software
            - name: stdenv-sion-csquare-run
              mountPath: /opt/stdenv
            - name: unpacked-sion-csquare-run
              mountPath: /opt/unpacked

          # Extra volumes
          volumes:
            - name: ca-cert
              secret:
                secretName: local-ca-secret
            - name: slurm-login-reindeer-profile
              configMap:
                name: slurm-login-reindeer-profile
                defaultMode: 493
            - name: slurm-login-reindeer-contlist
              configMap:
                name: slurm-login-reindeer-contlist
                defaultMode: 493
            - name: software-sion-csquare-run
              hostPath:
                path: /cvmfs/software.sion.csquare.run
                type: Directory
            - name: stdenv-sion-csquare-run
              hostPath:
                path: /cvmfs/stdenv.sion.csquare.run
                type: Directory
            - name: unpacked-sion-csquare-run
              hostPath:
                path: /cvmfs/unpacked.sion.csquare.run
                type: Directory
            - name: ldap-users-reindeer-pvc
              persistentVolumeClaim:
                claimName: ldap-users-reindeer-pvc
            - name: experiments-reindeer-pvc
              persistentVolumeClaim:
                claimName: experiments-reindeer-pvc
            - name: images-reindeer-pvc
              persistentVolumeClaim:
                claimName: images-reindeer-pvc
            - name: jobs-logs-reindeer-pvc
              persistentVolumeClaim:
                claimName: jobs-logs-reindeer-pvc

          net:
            # Kubernetes host interface
            masterInterface: eno2
            mode: bridge
            type: macvlan

            # https://www.cni.dev/plugins/current/ipam/static/
            ipam:
              type: host-local
              ranges:
                - - subnet: 10.10.2.0/24
                    rangeStart: 10.10.2.46
                    rangeEnd: 10.10.2.47
                    gateway: 10.10.2.1

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: slurm-cluster

  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions: []
    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 3m # the maximum amount of time allowed for the backoff strategy
