replicas: 1

dnsPolicy: 'None'
dnsConfig:
  nameservers:
    - 10.96.0.10
  options:
    - name: ndots
      value: '0'

nodeSelector:
  kubernetes.io/hostname: k0s-bare-ch-basel-1
  topology.kubernetes.io/region: ch-basel
  topology.kubernetes.io/zone: ch-basel-1

config:
  replicas:
    - name: repo.example.com
      url: https://cvmfs-0.example.com/cvmfs/repo.example.com
      keys: /etc/cvmfs/keys/example.com
      options: '-o root'

volumeMounts:
  - name: cvmfs-keys
    mountPath: /etc/cvmfs/keys/example.com
    readOnly: true

volumes:
  - name: cvmfs-keys
    secret:
      secretName: cvmfs-keys-secret
      defaultMode: 256

state:
  storageClassName: 'local-path'

storage:
  storageClassName: 'local-path'

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: production-cluster-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: 'true'

  ingressClass: 'traefik'

  hosts:
    - cvmfs-1.example.com

  tls:
    - secretName: cvmfs-1.example.com-secret
      hosts:
        - cvmfs-1.example.com
