apiVersion: v2
name: squid-subchart
description: Squid Proxy subchart
type: application
version: 0.1.0
appVersion: '0.1.2'

dependencies:
  - name: squid
    version: 0.1.2
    repository: https://registry.cern.ch/chartrepo/cern
