apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k8s.ch1.csquare.run-cluster
spec:
  hosts:
    - ssh:
        address: 10.10.2.16
        user: root
        port: 22
        keyPath: ~/.ssh/id_ed25519_csquare
      role: controller+worker
      installFlags:
        - --debug

  k0s:
    version: 1.23.5+k0s.0
    dynamicConfig: false
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: k8s.ch1.csquare.run
      spec:
        api:
          k0sApiPort: 9443
          port: 6443
        installConfig:
          users:
            etcdUser: etcd
            kineUser: kube-apiserver
            konnectivityUser: konnectivity-server
            kubeAPIserverUser: kube-apiserver
            kubeSchedulerUser: kube-scheduler
        konnectivity:
          adminPort: 8133
          agentPort: 8132
        network:
          calico:
            mode: 'vxlan'
            overlay: Always
            mtu: 0
            wireguard: false
          kubeProxy:
            disabled: false
            mode: iptables
          kuberouter:
            autoMTU: true
            mtu: 0
            peerRouterASNs: ''
            peerRouterIPs: ''
          podCIDR: 10.244.0.0/16
          provider: calico
          serviceCIDR: 10.96.0.0/12
        podSecurityPolicy:
          defaultPolicy: 00-k0s-privileged
        storage:
          type: etcd
        telemetry:
          enabled: false
        extensions:
          helm:
            repositories:
              - name: traefik
                url: https://helm.traefik.io/traefik
              - name: bitnami
                url: https://charts.bitnami.com/bitnami
              - name: jetstack
                url: https://charts.jetstack.io
              - name: csi-driver-nfs
                url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
              - name: cloudve
                url: https://github.com/CloudVE/helm-charts/raw/master
            charts:
              - name: metallb
                chartname: bitnami/metallb
                version: '2.6.8'
                namespace: metallb
                values: |
                  configInline:
                    address-pools:
                      - name: generic-cluster-pool
                        protocol: layer2
                        addresses:
                          - 10.10.2.100-10.10.2.105
                          - 10.10.2.152/32

                      - name: slurm-ips
                        protocol: layer2
                        addresses:
                          - 10.10.2.45-10.10.2.50

              - name: traefik
                chartname: traefik/traefik
                version: '10.15.0'
                namespace: traefik
                values: |
                  ingressClass:
                    enabled: true
                    isDefaultClass: true

                  service:
                    enabled: true
                    annotations:
                      metallb.universe.tf/address-pool: generic-cluster-pool
                      metallb.universe.tf/allow-shared-ip: traefik-lb-key
                    spec:
                      externalTrafficPolicy: Cluster
                      loadBalancerIP: 10.10.2.100
                    loadBalancerSourceRanges:
                      - 10.10.2.0/24

                  providers:
                    kubernetesCRD:
                      enabled: true
                      allowCrossNamespace: true
                      allowExternalNameServices: true
                      namespaces: []
                    kubernetesIngress:
                      enabled: true
                      allowExternalNameServices: true
                      namespaces: []
                      ingressClass: traefik
                      publishedService:
                        enabled: true

                  globalArguments:
                    - '--global.checknewversion'
                    - '--api.dashboard=true'

                  additionalArguments:
                    - '--entryPoints.websecure.proxyProtocol.insecure'
                    - '--entryPoints.websecure.forwardedHeaders.insecure'
                    - '--entrypoints.web.http.redirections.entryPoint.to=websecure'

                  ingressRoute:
                    dashboard:
                      enabled: false

                  ports:
                    traefik:
                      port: 9000
                      expose: false
                      exposedPort: 9000
                      protocol: TCP
                    web:
                      port: 80
                      expose: true
                      exposedPort: 80
                      protocol: TCP
                    websecure:
                      port: 443
                      expose: true
                      exposedPort: 443
                      protocol: TCP
                      # NOTE from csquare: use cert-manager.
                      tls:
                        enabled: false
                    metrics:
                      port: 9100
                      expose: false
                      exposedPort: 9100
                      protocol: TCP

                  securityContext:
                    capabilities:
                      drop: [ALL]
                      add: [NET_BIND_SERVICE]
                    readOnlyRootFilesystem: true
                    runAsGroup: 0
                    runAsNonRoot: false
                    runAsUser: 0

                  podSecurityContext:
                    fsGroup: 65532

              - name: cert-manager
                chartname: jetstack/cert-manager
                version: v1.7.1
                namespace: cert-manager
                values: |
                  installCRDs: true

              - name: csi-driver-nfs
                chartname: csi-driver-nfs/csi-driver-nfs
                version: 'v3.2.0'
                namespace: csi-driver-nfs
                values: |
                  driver:
                    mountPermissions: 0755
                  kubeletDir: /var/lib/k0s/kubelet

              - name: csi-driver-cvmfs
                chartname: cloudve/galaxy-cvmfs-csi
                version: '1.6.0'
                namespace: csi-driver-cvmfs
                values: |
                  repositories:
                    software-sion-csquare-run: software.sion.csquare.run
                    unpacked-sion-csquare-run: unpacked.sion.csquare.run
                    stdenv-sion-csquare-run: stdenv.sion.csquare.run

                  configs:
                    software-sion-csquare-run-keys:
                      mountPath: keys/software.sion.csquare.run.pub
                      contents: |
                        -----BEGIN PUBLIC KEY-----
                        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsZFcmI0L6L1XjmeH7dWn
                        vBWAk6HTC85pcFYJXg9sQ3lBKj+F/Ir6Gd5CEKb4pZ0E7hOeVyTNFrfMFegjinxW
                        XFHw3z1IcaJnI8mq3BIzFKFyAVxvaVkemXoQ2g47T78+IZDLLiEjgAbu/wNGfOl8
                        L7mVxFvsN7iv6FQD5fNS9KoKaBniwF2zwg2IC3CUolraQxOW9GMlkIr0Qh/Fj1cG
                        znDLEYC0iEdNzHOzWM9E2oNibMlBtd354Ff5hRuag3qQPGGCy3WRmlLMV6hi7fM3
                        KFxVqH2s16/9i9KLo+hc/n7gDSQzMeRQyfxaTE2rXsP2RrXQBs33e/YIaooGpxVZ
                        VwIDAQAB
                        -----END PUBLIC KEY-----
                    unpacked-sion-csquare-run-keys:
                      mountPath: keys/unpacked.sion.csquare.run.pub
                      contents: |
                        -----BEGIN PUBLIC KEY-----
                        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzdcgATB2fEESkNoft7HE
                        Z+7itxvzXOE9Lp9yvXHXpYXDWzRtMCp2Hi71FM1GlM923wSfMlGu1JDYNjtoZube
                        sF0K4AdHxkTTkgMetKx0VnntP/kXaBW0yYucZFN7nqk9tGO3g9j5a8uSCnizDrOa
                        h/GzJ+6pwmr5JH86XA/qZMOj79vCkmI/wteCQzTSVvYHRw/udfPLbNcI3AAH2MyA
                        AMr+ethcrBIQoRj+z/mfeTPJeYjbuDQ1TP4Btf3ft0jtDB4i59/vo6+Aq3XwmhZE
                        kwmOSP0qqJ+X661ubhgy7SYBC2C6SIV6Ot2RI37/Dc7T2IjXAQ373KXUm/PWU9Zy
                        gwIDAQAB
                        -----END PUBLIC KEY-----
                    stdenv-sion-csquare-run-keys:
                      mountPath: keys/stdenv.sion.csquare.run.pub
                      contents: |
                        -----BEGIN PUBLIC KEY-----
                        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAx6C5dzgUXJ4qtG92EjpC
                        baE7u7hleKivcARLvjovgTN8K7Zup7SWuc7XxJCZ7pRCbl7d0R4f4ii5rA99z4uu
                        cTdoESkXx56c5Q/115WT7YSumab68xfs05PActTKLBUFOph4/aoJFjchtn3pu/qC
                        y3/ELxGIrAlNJEbuCO1py15l9KoTcxl8LGapsWQR93aoxPU4IxKxzxrj0OwVGodk
                        dGvVRhHuGFJkHhDu57opfxktwd4pnNPLI8w+CEvm0OVKASaQdjwhAK3655T0Jq6G
                        qQxvlIo26sOT/R+6WvDNKzjQwRTpP8TXuC00o5exNAdLkKapWfD+lj3K+sLF2ubl
                        /QIDAQAB
                        -----END PUBLIC KEY-----
                    software-sion-csquare-run-config:
                      mountPath: config.d/software.sion.csquare.run.conf
                      contents: |
                        CVMFS_HTTP_PROXY="${CVMFS_HTTP_PROXY:=DIRECT}"
                        CVMFS_SERVER_URL=http://cvmfs.ch1.csquare.run/cvmfs/software.sion.csquare.run
                    unpacked-sion-csquare-run-config:
                      mountPath: config.d/unpacked.sion.csquare.run.conf
                      contents: |
                        CVMFS_HTTP_PROXY="${CVMFS_HTTP_PROXY:=DIRECT}"
                        CVMFS_SERVER_URL=http://cvmfs.ch1.csquare.run/cvmfs/unpacked.sion.csquare.run
                    stdenv-sion-csquare-run-config:
                      mountPath: config.d/stdenv.sion.csquare.run.conf
                      contents: |
                        CVMFS_HTTP_PROXY="${CVMFS_HTTP_PROXY:=DIRECT}"
                        CVMFS_SERVER_URL=http://cvmfs.ch1.csquare.run/cvmfs/stdenv.sion.csquare.run

                  cache:
                    alienCache:
                      enabled: false
                    localCache:
                      enabled: false

                  csiPlugin:
                    nodeDriverImage: quay.io/k8scsi/csi-node-driver-registrar:v2.1.0
                    pluginDirectory: /var/lib/k0s/kubelet/plugins/csi-cvmfsplugin
                  csiAttacher:
                    image: quay.io/k8scsi/csi-attacher:v3.1.0
                    args:
                      - '--csi-address=$(ADDRESS)'
                      - '--v=5'
                  csiProvisioner:
                    image: quay.io/k8scsi/csi-provisioner:v2.1.2
                    args:
                      - '--v=5'
                      - '--csi-address=$(ADDRESS)'
