apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k8s.ch1.csquare.run-cluster
spec:
  hosts:
    - ssh:
        address: 10.10.2.16
        user: root
        port: 22
        keyPath: ~/.ssh/id_ed25519_csquare
      role: controller+worker
      privateInterface: eno2
      privateAddress: 10.10.2.16
      installFlags:
        - --debug
        - --labels="topology.kubernetes.io/region=ch-sion,topology.kubernetes.io/zone=ch-sion-1"
      hooks:
        apply:
          after:
            - mkdir -p /var/lib/k0s/kubelet
            - sh -c "if [ -L /var/lib/kubelet ]; then echo symlink already exists; else rm -f /var/lib/kubelet && ln -s /var/lib/k0s/kubelet /var/lib/kubelet; fi"
            - sh -c 'if [ "$(getenforce)" -nq "Permissive" ]; then sed -i s/^SELINUX=.*$/SELINUX=permissive/ /etc/selinux/config; fi'
            - sh -c 'if [ "$(getenforce)" -nq "Permissive" ]; then setenforce 0; fi'
    - ssh:
        address: 172.24.0.4
        user: root
        port: 22
        keyPath: ~/.ssh/id_ed25519_csquare
      role: worker
      privateInterface: priv0
      privateAddress: 172.24.0.4
      installFlags:
        - --debug
        - --labels="topology.kubernetes.io/region=at-vie,topology.kubernetes.io/zone=at-vie-1"
      hooks:
        apply:
          after:
            - mkdir -p /var/lib/k0s/kubelet
            - sh -c "if [ -L /var/lib/kubelet ]; then echo symlink already exists; else rm -f /var/lib/kubelet && ln -s /var/lib/k0s/kubelet /var/lib/kubelet; fi"
            - sh -c 'if [ "$(getenforce)" -nq "Permissive" ]; then sed -i s/^SELINUX=.*$/SELINUX=permissive/ /etc/selinux/config; fi'
            - sh -c 'if [ "$(getenforce)" -nq "Permissive" ]; then setenforce 0; fi'

  k0s:
    version: 1.23.6+k0s.1
    dynamicConfig: false
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: k8s.ch1.csquare.run
      spec:
        api:
          k0sApiPort: 9443
          port: 6443
        installConfig:
          users:
            etcdUser: etcd
            kineUser: kube-apiserver
            konnectivityUser: konnectivity-server
            kubeAPIserverUser: kube-apiserver
            kubeSchedulerUser: kube-scheduler
        konnectivity:
          adminPort: 8133
          agentPort: 8132
        network:
          calico:
            mode: 'vxlan'
            overlay: Always
            mtu: 0
            wireguard: false
          kubeProxy:
            disabled: false
            mode: iptables
          kuberouter:
            autoMTU: true
            mtu: 0
            peerRouterASNs: ''
            peerRouterIPs: ''
          podCIDR: 10.244.0.0/16
          provider: calico
          serviceCIDR: 10.96.0.0/12
        podSecurityPolicy:
          defaultPolicy: 00-k0s-privileged
        storage:
          type: etcd
        telemetry:
          enabled: false
        extensions:
          helm:
            repositories:
              - name: traefik
                url: https://helm.traefik.io/traefik
              - name: bitnami
                url: https://charts.bitnami.com/bitnami
              - name: jetstack
                url: https://charts.jetstack.io
              - name: csi-driver-nfs
                url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
              - name: cloudve
                url: https://github.com/CloudVE/helm-charts/raw/master
            charts:
              - name: metallb
                chartname: bitnami/metallb
                version: '3.0.4'
                namespace: metallb
                values: |
                  configInline:
                    peers:
                      - peer-address: 172.24.0.2
                        peer-asn: 65007
                        my-asn: 64500
                        source-address: 172.24.0.4
                        node-selectors:
                          - match-labels:
                              kubernetes.io/hostname: k0s-exoscale-at-vie-1

                      - peer-address: 10.10.2.1
                        peer-asn: 65503
                        my-asn: 64501
                        source-address: 10.10.2.16
                        node-selectors:
                          - match-labels:
                              kubernetes.io/hostname: mn1.ch1.csquare.run

                    address-pools:
                      - name: main-pool
                        protocol: bgp
                        addresses:
                          - 10.10.4.100/32

              - name: traefik
                chartname: traefik/traefik
                version: '10.19.5'
                namespace: traefik
                values: |
                  ingressClass:
                    enabled: true
                    isDefaultClass: true

                  service:
                    enabled: true
                    annotations:
                      metallb.universe.tf/address-pool: main-pool
                      metallb.universe.tf/allow-shared-ip: traefik-lb-key
                    spec:
                      externalTrafficPolicy: Cluster
                      loadBalancerIP: 10.10.4.100

                  providers:
                    kubernetesCRD:
                      enabled: true
                      allowCrossNamespace: true
                      allowExternalNameServices: true
                      namespaces: []
                    kubernetesIngress:
                      enabled: true
                      allowExternalNameServices: true
                      namespaces: []
                      ingressClass: traefik
                      publishedService:
                        enabled: true

                  globalArguments:
                    - '--global.checknewversion'
                    - '--api.dashboard=true'

                  additionalArguments:
                    - '--entryPoints.websecure.proxyProtocol.insecure'
                    - '--entryPoints.websecure.forwardedHeaders.insecure'

                  ingressRoute:
                    dashboard:
                      enabled: false

                  ports:
                    traefik:
                      port: 9000
                      expose: false
                      exposedPort: 9000
                      protocol: TCP
                    dns-tcp:
                      port: 8053
                      expose: true
                      exposedPort: 53
                      protocol: TCP
                    dns-udp:
                      port: 8054
                      expose: true
                      exposedPort: 53
                      protocol: UDP
                    oidc:
                      port: 5556
                      expose: true
                      exposedPort: 5556
                      protocol: TCP
                    web:
                      port: 80
                      expose: true
                      exposedPort: 80
                      protocol: TCP
                    websecure:
                      port: 443
                      expose: true
                      exposedPort: 443
                      protocol: TCP
                      # NOTE: use cert-manager.
                      tls:
                        enabled: false
                    metrics:
                      port: 9100
                      expose: false
                      exposedPort: 9100
                      protocol: TCP

                  securityContext:
                    capabilities:
                      drop: [ALL]
                      add: [NET_BIND_SERVICE]
                    readOnlyRootFilesystem: true
                    runAsGroup: 0
                    runAsNonRoot: false
                    runAsUser: 0

                  podSecurityContext:
                    fsGroup: 65532

              - name: cert-manager
                chartname: jetstack/cert-manager
                version: v1.8.0
                namespace: cert-manager
                values: |
                  installCRDs: true

              - name: csi-driver-nfs
                chartname: csi-driver-nfs/csi-driver-nfs
                version: 'v4.0.0'
                namespace: csi-driver-nfs
                values: |
                  driver:
                    mountPermissions: 0775
                  kubeletDir: /var/lib/k0s/kubelet
