apiVersion: 'k8s.cni.cncf.io/v1'
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-test
  namespace: kube-system
spec:
  config: |
    {
      "cniVersion": "0.4.0",
      "capabilities": { "ips": true, "dns": true, "mac": true, "ipRanges": true },
      "plugins": [
        {
          "type": "macvlan",
          "master": "eno2",
          "mode": "bridge",
          "ipam": {
            "type": "host-local",
            "ranges": [
              [
                {
                  "subnet": "10.10.2.0/24",
                  "rangeStart": "10.10.2.240",
                  "rangeEnd": "10.10.2.249",
                  "gateway": "10.10.2.1"
                }
              ]
            ],
            "routes": [
              { "dst": "0.0.0.0/0" }
            ],
            "resolvConf": "/etc/resolv.conf"
          }
        }
      ]
    }
---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: fedora
  namespace: kube-system
spec:
  domain:
    cpu:
      cores: 1
      model: host-model
      sockets: 2
      threads: 1
    devices:
      disks:
        - disk:
            bus: virtio
          name: containerdisk
        - disk:
            bus: virtio
          name: cloudinitdisk
      interfaces:
        - bridge: {}
          name: macvlan-net
    resources:
      limits:
        memory: 4Gi
      requests:
        memory: 4Gi
  networks:
    - name: macvlan-net
      multus:
        default: true
        networkName: kube-system/macvlan-test
  terminationGracePeriodSeconds: 0
  volumes:
    - containerDisk:
        image: quay.io/kubevirt/fedora-cloud-container-disk-demo:20210811_9fec1f849
        imagePullPolicy: IfNotPresent
      name: containerdisk
    - cloudInitNoCloud:
        userData: |
          #cloud-config
          password: fedora
          chpasswd: { expire: False }
      name: cloudinitdisk
