apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgA7UfsewAhr5GXk531IOs4Y/cw8ZESFGgeZ9iS46PGGVTg6VUtSDOyog+KRw4ETiHfJdwnLfhRbFVxrOJzCBKJI5Ulg6of1dvQwQuNKdyPn/Ih4Kj0H0LAcAomHVV9XtwUkLwIeI7jOJACa4r9tNzoRfyYhxZZ9BYELE/KbJNx3U2xFYE0pU2AF6aAiVxiGFJsVh89iyTPXge1NDqXc56k79sCrDBqfpEqcIrSiIODHaBMfO1p1hhtpwozcy9Hdgkn2xeqKzyBSABM2EnueZrXqTp4zGjKlonIn+Z4S0qFRn4ZJW8aBgTtK7isQFkXIxNLqeD+6kixez2S8eZ24+5XOFHEKOQxH47Xf1NNxP59ZqW9Otn1S0hhZHzIX+XoKGiIhNVwIMHbnZCHhxW9g/eYn78dcWfkXyLR3lsKtvQAE7ponKO88TtIcMNCh4S23HBZ9gCaXu9R16mWj8P5kUhMs8JkX3oqUcp3NeQ9nHr1IKsjXxGV/foYCrsX+cUEQitu0CWOAacOjGIracX8bSsjtvUg3ZyUFQqY3k9qL40t7Vn10uqtTXFNlETozh4Yj9yIa6FkqHvaEZtbPQZ+kZu17Rw+GhC7lN0hTFDOPd/yo+rYIQTNlJrQ3FCVwf5IqiED+L14tWaEO2DjkpJBEFs93rPghDtB4MOUCgU6wprugXGDNf2iMdfb6YnyoTbYve/qeeyEGTQs4PkdKrg780laYqlMxQYbperyJOevaCTR5fw==
    admin-user: AgBwMDYLavith0EMeQ21njvQvdxglr281/QdF0soJQoOQTK9lpUYZyetJq8KJ1KhhoMY8AhZkAnDE0tfxJTSf1SqY6TERBTOqanYc99NpM7xh62Q6fHlh7vMZCMUm3t/Hm0MgvOQsSeB8iYXDxY7SFP00FOA8pcSXfzrKTlyfqiflYSfkGy7DyEo2KPebWRB+GzWggynwoYm4Sjfb3vfaPybvEMWxUnIvCWUIqZ19dA0VlmLN+tqNiz54nn9ZKf5QEyUFn1R7L8AdDtVafY2GbK1mzJbOW6MQwayR4T1WG1a+R0bdj48BKMZ1Y3EeXX9Gvpn/XyG4laDDqhN94TzJo2aTubc5pBtSPKubjZigQCCuRPr4N7OKda7HNC3X5o6TDgF7qzmzy/u3fut4ei/8eiPMxGzL4E0ODDcSwiCRsY8Hh9W4HQact18WL2BlLlT9Zv3+wtIkUqautiaXhxAze6i+0TjXzAgiGymDvvpRZMdtbL+CIXRXuGDLNPVy+SgetXzeSPotvqaQxcZLf2KpTWLhhRbTcad9tblO0lu5dznivWUrhBakch9nTrwP5r7JP67q7o2eULjmMZOBuYrGHqzWdNEIp1ZOHfsjDYQc0N4UBU61Ong06s/gMIwJq0Ht0WevfSg9YwlU6Osseq8WdX/oHoWezOm4Nv0W+jxldvOSmWCoTktEWViOQu3aQDizdBk10cKAQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque

