apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-marc-secret
  namespace: slurm-cluster
spec:
  encryptedData:
    .dockerconfigjson: AgCsbd8RoLyDa4w7P3amfGsQH+/dSt8Lu0zQBySm05h9xhvFL0h6Wh1GAdSF2/ZDZ+6lxEK0wH62oNTj7vE7l02zHDkPry6Npozi51MFxAqmkYlR8+9lfQiQaZCF0smwVJpLGjonk5KMyQ56/XNj7U5uGWlFeHsuUZ6kFGB5vhSKwisl8TI7P+ZMA4ZGsL00VYgdokQidmhr1udysbGz+ZA4zpIfFUsqTkFVpW51Ok2uHmhNGt4sFBB0Y2cRII0FmWpn5jxOq4D2Z4w3hwWJINne+wjcmaspRTq2KpZy50q6gxEL3I2OJbNZZn6/Wfuz4K622xaANZXGLxdcCW6Zfi/17kbXLtS/ljdnomvfafKmsR+PjKLe7Kr4RnxSvZampH2YqeRJJZSJNtekoThj2EtTHDhTowuucoJZfeNDvJ/gN/82q6Z0/loPMSU/guMbDSXolENfG5uGYGh3D1FOCQCWp5megzreiydU7EntLwE5HtZHYITyf408EPba/0IYu+cL8KmTLIe7ScdlUwxGE7Aj1BqbXjI59iLMjfLXkOf3hfijtsBVzkR+mIaYJSsKD3Zu4lTAzRlu45evuumzgISAT4qebOn9R47keqQIP0vhQVJ8AxMHP7ytSP1u0C+lw9rUjVkAfJ0XfeAaeDr+X1u7Y1Uh5+vvtfAtyZkRqAUnI3fRvGpuZoPIxjlvFJKGJi1bdN5GgH8Eb8fmpbeTpZENXZl0lgvEhMJMREFfOO102ZK58vmwvNmgrsdihs4cVtiLK+4U0C9/HhoS2xKJNWoSNHE82wun3NCjGTHb0Ms47FNQXCgczqaxO8+C2U+FQxw67WtXBVqAM5eSHt/8OsHAQUBR+RZI+RFg3x1Z0LAX6noAyxBLk1uO+7g62u2q02Q4fY0MDAhjfm3Zm10tWPLSCaSKLg5LVQV60ilGEKfohXHj7Rkyzp4TDY73sTOnNdKCmU58Y54bcLkSqs2xbEtk
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ghcr-marc-secret
      namespace: slurm-cluster
    type: kubernetes.io/dockerconfigjson
