apiVersion: v2
name: keycloak
description: Open Source Identity and Access Management For Modern Applications and Services.
type: application
home: https://www.keycloak.org
sources:
  - https://github.com/keycloak/keycloak
version: 0.1.0
appVersion: '20.0.3'
maintainers:
  - name: Marc Nguyen
    email: marc@squarefactory.io
  - name: Christophe Lillo
    email: lillo@squarefactory.io
