apiVersion: v1
kind: PersistentVolume
metadata:
  name: controller-state-reindeer-pv
  namespace: slurm-cluster
  labels:
    app: slurm-controller
    failure-domain.beta.kubernetes.io/region: ch-sion
    failure-domain.beta.kubernetes.io/zone: ch-sion-1
spec:
  capacity:
    storage: 50Gi
  mountOptions:
    - hard
    - nfsvers=4.1
    - noatime
    - nodiratime
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: aedc7299-5f78-4097-8aa9-e28d942c18c3
    volumeAttributes:
      server: 10.10.2.11
      share: '/mnt/pool1/k8s/slurmctl'
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
