{{- if and .Values.ondemand.enabled .Values.ondemand.httpIngress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ template "slurm-cluster.ondemand.name" . }}-http"
  namespace: '{{ .Release.Namespace }}'
  labels:
    release: '{{ .Release.Name }}'
    chart: '{{ .Chart.Name }}'
    app: "{{ template "slurm-cluster.ondemand.name" . }}"
{{- if .Values.ondemand.httpIngress.annotations }}
  annotations:
{{ toYaml .Values.ondemand.httpIngress.annotations | indent 4 }}
{{- end }}
spec:
  ingressClassName: "{{ .Values.ondemand.httpIngress.ingressClass }}"
  rules:
    {{- range $host := .Values.ondemand.httpIngress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ template "slurm-cluster.ondemand.name" $ }}"
                port:
                  name: http
    {{- end }}
  {{- if .Values.ondemand.httpIngress.tls }}
  tls:
{{ toYaml .Values.ondemand.httpIngress.tls | indent 4 }}
  {{- end }}
{{- end }}
---
{{- if and .Values.ondemand.enabled .Values.ondemand.oidcIngress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ template "slurm-cluster.ondemand.name" . }}-oidc"
  namespace: '{{ .Release.Namespace }}'
  labels:
    release: '{{ .Release.Name }}'
    chart: '{{ .Chart.Name }}'
    app: "{{ template "slurm-cluster.ondemand.name" . }}"
{{- if .Values.ondemand.oidcIngress.annotations }}
  annotations:
{{ toYaml .Values.ondemand.oidcIngress.annotations | indent 4 }}
{{- end }}
spec:
  ingressClassName: "{{ .Values.ondemand.oidcIngress.ingressClass }}"
  rules:
    {{- range $host := .Values.ondemand.oidcIngress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ template "slurm-cluster.ondemand.name" $ }}"
                port:
                  name: oidc
    {{- end -}}
  {{- if .Values.ondemand.oidcIngress.tls }}
  tls:
{{ toYaml .Values.ondemand.oidcIngress.tls | indent 4 }}
  {{- end }}
{{- end }}
