kind: ConfigMap
apiVersion: v1
metadata:
  name: 'slurm-login-reindeer-contlist'
  namespace: 'slurm-cluster'
  labels:
    failure-domain.beta.kubernetes.io/region: ch-sion
    failure-domain.beta.kubernetes.io/zone: ch-sion-1
data:
  contlist:
    #!/bin/sh
    find /opt/unpacked -maxdepth 3 -mindepth 3 -name "*:*" | cut -d "/" -f 4- | grep "$1"
