apiVersion: v1
kind: PersistentVolume
metadata:
  name: experiments-pv
  namespace: slurm-cluster
  labels:
    app: slurm-login
spec:
  capacity:
    storage: 1000Gi
  mountOptions:
    - hard
    - nfsvers=4.1
    - noatime
    - nodiratime
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: 19d01850-e30c-4e77-92b5-f68d48ac0083
    volumeAttributes:
      server: 10.10.2.11
      share: '/mnt/pool1/compute-nodes/experiments'
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
