apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: images-pvc
  namespace: slurm-cluster
  labels:
    app: slurm-login
spec:
  volumeName: images-pv
  accessModes: [ReadWriteMany]
  storageClassName: ''
  resources:
    requests:
      storage: 1000Gi
