apiVersion: v1
kind: PersistentVolume
metadata:
  name: images-pv
  namespace: slurm-cluster
  labels:
    app: slurm-login
spec:
  capacity:
    storage: 1000Gi
  mountOptions:
    - hard
    - nfsvers=4.1
    - noatime
    - nodiratime
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: 33c091d1-6d90-403f-87d0-86ff5dce517f
    volumeAttributes:
      server: 10.10.2.11
      share: '/mnt/pool1/compute-nodes/images'
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
