apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jobs-logs-pvc
  namespace: slurm-cluster
  labels:
    app: slurm-login
spec:
  volumeName: jobs-logs-pv
  accessModes: [ReadWriteMany]
  storageClassName: ''
  resources:
    requests:
      storage: 1000Gi
