kind: ConfigMap
apiVersion: v1
metadata:
  name: 'slurmctl-exoscale-vie-powersave'
  namespace: 'slurm-cluster'
  labels:
    failure-domain.beta.kubernetes.io/region: at-vie
    failure-domain.beta.kubernetes.io/zone: at-vie-1
data:
  resume.sh: |
    #!/bin/bash -ex

    echo "Resume script called with the parameters: $@" >> /var/log/powersave.log

    hosts=$(scontrol show hostnames $1)
    for host in $hosts
    do
      ssh -i /slurm-ssh-dir/id_rsa -o StrictHostKeyChecking=no slurmctl@172.20.0.10 "sudo /slurm_powersave/resume.sh '$host'" >> /var/log/resume.log &
    done

    echo "Resume script finished with the parameters: $@" >> /var/log/powersave.log
  suspend.sh: |
    #!/bin/bash -e

    echo "Suspend script called with the parameters: $@" >> /var/log/powersave.log

    hosts=$(scontrol show hostnames $1)
    for host in $hosts
    do
      ssh -i /slurm-ssh-dir/id_rsa -o StrictHostKeyChecking=no slurmctl@172.20.0.10 "sudo /slurm_powersave/suspend.sh '$host'" >> /var/log/suspend.log &
    done
    echo "Suspend script finished with the parameters: $@" >> /var/log/powersave.log
