kind: ConfigMap
apiVersion: v1
metadata:
  name: 'slurmctl-exoscale-vie-epilogs'
  namespace: 'slurm-cluster'
  labels:
    failure-domain.beta.kubernetes.io/region: at-vie
    failure-domain.beta.kubernetes.io/zone: at-vie-1
data:
  beeond: |
    #!/bin/bash

    export PATH="$PATH:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin"

    nodefile="/var/spool/slurmctl/beeond/slurm_nodelist.${SLURM_JOB_ID}"
    logfile="/var/log/beeond.log"

    if [ -e "$nodefile" ]; then
      sudo beeond stop -b /usr/bin/pdsh -n "${nodefile}" -d -P -L -c >> $logfile 2>&1
      rm -f "$nodefile"
    else
      echo "warning: no nodefile found for job ${SLURM_JOB_ID}" >> $logfile
    fi
