kind: ConfigMap
apiVersion: v1
metadata:
  name: 'slurmctl-exoscale-vie-sbin'
  namespace: 'slurm-cluster'
  labels:
    topology.kubernetes.io/region: at-vie
    topology.kubernetes.io/zone: at-vie-1
data:
  start-beeond-in-bg: |
    #!/bin/bash -x

    export PATH="$PATH:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin"

    # Store pid to see any zombies
    echo $$ > "/run/slurmctl/beeond.${SLURM_JOB_ID}.pid"

    nodefile="/var/spool/slurmctl/beeond/slurm_nodelist.${SLURM_JOB_ID}"
    datadir="/mnt/scratch/beeond"
    clientdir="/opt/cache/datasets"

    mkdir -p "$(dirname "$nodefile")"

    scontrol show hostnames "${SLURM_JOB_NODELIST}" > "${nodefile}"
    timeout 60 sudo beeond stop -b /usr/bin/pdsh -n "${nodefile}" -d -P -L -c || echo "beeond stop failed but we are going to ignore that"
    timeout 60 sudo beeond start -b /usr/bin/pdsh -n "${nodefile}" -d "${datadir}" -c "${clientdir}" -P -F

    rm "/run/slurmctl/beeond.${SLURM_JOB_ID}.pid"
