kind: ConfigMap
apiVersion: v1
metadata:
  name: 'slurmctl-exoscale-vie-prologs'
  namespace: 'slurm-cluster'
  labels:
    failure-domain.beta.kubernetes.io/region: at-vie
    failure-domain.beta.kubernetes.io/zone: at-vie-1
data:
  beeond: |
    #!/bin/bash

    set -ex

    export PATH="$PATH:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin"

    nodefile="/tmp/slurm_nodelist.${SLURM_JOB_ID}"
    datadir="/mnt/scratch/beeond"
    clientdir="/opt/scratch"
    logfile="/var/log/beeond/beeond.log"

    scontrol show hostnames "${SLURM_JOB_NODELIST}" > "${nodefile}"

    scontrol wait_job $SLURM_JOB_ID
    timeout 60 sudo beeond start -n "${nodefile}" -d "${datadir}" -c "${clientdir}" -P -F >> $logfile 2>&1
