kind: ConfigMap
apiVersion: v1
metadata:
  name: 'slurmctl-exoscale-vie-prologs'
  namespace: 'slurm-cluster'
  labels:
    topology.kubernetes.io/region: at-vie
    topology.kubernetes.io/zone: at-vie-1
data:
  beeond: |
    #!/bin/bash

    export PATH="$PATH:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin"

    logfile="/var/log/beeond.log"
    mkdir -p /var/spool/slurmctl/screen
    chmod 700 /var/spool/slurmctl/screen
    export SCREENDIR=/var/spool/slurmctl/screen
    screen -L -Logfile "${logfile}" -dmS "beeond.${SLURM_JOB_ID}" /usr/local/sbin/start-beeond-in-bg
    sleep 1
