apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-multus-ds
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: kube-multus
          resources:
            requests:
              cpu: '100m'
              memory: '200Mi'
            limits:
              cpu: '100m'
              memory: '200Mi'
