apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openldap-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ldap
  source:
    repoURL: git@github.com:squarefactory/cluster-factory-ce.git
    targetRevision: HEAD
    path: helm/openldap
    helm:
      releaseName: openldap

      values: |
        replicas: 1

        nodeSelector:
          topology.kubernetes.io/region: ch-sion
          topology.kubernetes.io/zone: ch-sion-1

        env:
          BITNAMI_DEBUG: 'true'
          LDAP_ROOT: 'dc=example,dc=org'
          LDAP_CONFIG_ADMIN_ENABLED: 'no'
          LDAP_USER_DC: 'users'
          LDAP_GROUP: 'readers'
          LDAP_ADD_SCHEMAS: 'yes'
          LDAP_EXTRA_SCHEMAS: 'cosine,inetorgperson,nis'
          LDAP_SKIP_DEFAULT_TREE: 'no'
          LDAP_CUSTOM_LDIF_DIR: '/ldifs'
          LDAP_CUSTOM_SCHEMA_FILE: '/schema/custom.ldif'
          LDAP_ULIMIT_NOFILES: '1024'
          LDAP_ALLOW_ANON_BINDING: 'yes'
          LDAP_LOGLEVEL: '256'

        persistence:
          storageClassName: 'openldap-nfs'

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ldap

  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions: []
    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 3m # the maximum amount of time allowed for the backoff strategy
