apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system-coredns
  labels:
    k0s.k0sproject.io/stack: coredns
    kubernetes.io/bootstrapping: rbac-defaults
rules:
  - verbs:
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - endpoints
      - services
      - pods
      - namespaces
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - nodes
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - list
      - watch
