apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pv-claim
  namespace: monitoring
spec:
  volumeName: grafana-pv
  storageClassName: ''
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
