---
replicas: 1

image: 'ghcr.io/squarefactory/xcat-rocky:0.1.3-xcat2.16.3-rocky8.4'
imagePullPolicy: 'IfNotPresent'

podAnnotations: {}

# additionals labels
labels: {}

resources:
  requests:
    cpu: '2'
    memory: '8Gi'
  limits:
    cpu: '2'
    memory: '8Gi'

# This is the node affinity settings as defined in
# https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity-beta-feature
nodeAffinity: {}

updateStrategy: RollingUpdate

podSecurityContext:
  fsGroup: 0
  runAsUser: 0

securityContext:
  capabilities:
    add:
      - CAP_SYS_ADMIN
      - NET_ADMIN
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  runAsUser: 0

# How long to wait for xcat to stop gracefully
terminationGracePeriod: 10

## Use an alternate scheduler.
## ref: https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
##
schedulerName: ''

imagePullSecrets: {}

# Try to use nodeSelector to filter the hosts without the master interface
nodeSelector: {}
tolerations: []

tmp:
  medium: ''
  size: 50Gi

persistence:
  storageClassName: ''
  accessModes: ['ReadWriteOnce']
  size: 50Gi
  selectorLabels:
    app: xcat

net:
  # Kubernetes host interface
  masterInterface: eth0
  mode: bridge

  # https://www.cni.dev/plugins/current/ipam/static/
  ipam:
    type: static
    addresses:
      - address: 10.10.2.2/24
        gateway: 10.10.2.1
    routes:
      - dst: 0.0.0.0/0
      - dst: 10.10.2.0/24
        gw: 10.10.2.1

  # https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config
  dns:
    nameservers:
      - 1.1.1.1
    searches:
      - example.com
