kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ template "slurm-cluster.name" . }}-slurmctl-epilogs"
  namespace: '{{ .Release.Namespace }}'
  labels:
    release: '{{ .Release.Name }}'
    chart: '{{ .Chart.Name }}'
data:
  beeond: |
    #!/bin/bash

    export PATH="$PATH:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin"

    nodefile="/tmp/slurm_nodelist.${SLURM_JOB_ID}"
    #datadir="/mnt/scratch/beeond"
    #clientdir="/opt/scratch"
    logfile="/var/log/beeond/beeond.log"

    if [ -e "$nodefile" ] ; then
      sudo beeond stop -n "${nodefile}" -d -P -L -c >> $logfile 2>&1 || echo "Beeond failed" >> $logfile
      rm -f "$nodefile"
    fi
