{{- if .Values.service.enabled }}
{{- $serviceValues := .Values.service -}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "389ds.name" $ }}"
  labels:
    app: "{{ template "389ds.name" $ }}"
spec:
  type: {{ $serviceValues.type }}
  {{- if $serviceValues.clusterIP }}
  clusterIP: {{ $serviceValues.clusterIP }}
  {{- end }}
  {{- if $serviceValues.externalIPs }}
  externalIPs:
  {{ toYaml $serviceValues.externalIPs | indent 4 }}
  {{- end }}
  {{- if $serviceValues.loadBalancerIP }}
  loadBalancerIP: {{ $serviceValues.loadBalancerIP }}
  {{- end }}
  {{- if $serviceValues.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := $serviceValues.loadBalancerSourceRanges }}
    - {{ $cidr }}
  {{- end }}
  {{- end }}
  {{- if ne $serviceValues.type "ClusterIP" }}
  externalTrafficPolicy: {{ $serviceValues.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: 3389
      targetPort: ldap
      protocol: TCP
      name: ldap
    - port: 3636
      targetPort: ldaps
      protocol: TCP
      name: ldaps
  selector:
    app: "{{ template "389ds.name" $ }}"
{{- end }}
